adobe/aio-lib-web

package.json

Filled package.json details  📦

---

jest.config.js
lib/tvm-client.js
test/common.test.js
test/lib/remote-storage.test.js
test/lib/tvm-client.test.js
test/scripts/build.actions.test.js
test/scripts/build.ui.test.js
test/scripts/deploy.actions.test.js
test/scripts/deploy.ui.test.js
test/scripts/undeploy.actions.test.js
test/scripts/undeploy.ui.test.js

Added missing license headers

---

lib/config-loader.js
package-lock.json
package.json
scripts/deploy.actions.js
scripts/undeploy.actions.js
test/__fixtures__/sample-app/manifest.yml
test/scripts/build.ui.test.js

Support for action sequences 
Make action sequence urls available to the UI in the same way as regular actions are
https://github.com/adobe/adobeio-cna-starter-project/issues/19
added unit test to check for build ui generated config to include a sequence URL

Action sequences support

---

lib/abstract-script.js
lib/config-loader.js
package-lock.json
test/__fixtures__/sample-app/web-src/src/App.js

Fix missing dir for autogen ui config

---

lib/config-loader.js

User can specify aio config: `cna.actions`, `cna.dist`, `cna.web`
before missed cna prefix

User config fix

---

README.md
lib/abstract-script.js
scripts/deploy.ui.js

no path arg, messages on stderr, better end event

---

.gitignore
README.md
index.js
lib/abstract-script.js
lib/config-loader.js
lib/utils.js
package-lock.json
package.json
scripts/build.ui.js
scripts/deploy.actions.js
scripts/deploy.ui.js
scripts/dev.js

Dev server real

---

.gitignore
index.js
scripts/add.auth.js
test/scripts/add.auth.test.js

Users can now add auth to their manifest.

[ACNA-357] Adding Auth

---

README.md

Update readme, install, usage #14

---

lib/remote-storage.js
lib/tvm-client.js
package-lock.json
package.json
test/__fixtures__/sample-app/actions/action-zip/index.js

This closes #11.
This closes #12.

joi to @hapi/joi, relax node10 requirement

---

.travis.yml
README.md
bin/cna-scripts.js
index.js
lib/abstract-script.js
lib/config-loader.js
lib/utils.js
package.json
scripts/add.auth.js
scripts/build.actions.js
scripts/build.ui.js
scripts/deploy.actions.js
scripts/deploy.ui.js
scripts/dev.js
scripts/undeploy.actions.js
scripts/undeploy.ui.js
test/common.test.js
test/index.test.js
test/scripts/add.auth.test.js
test/scripts/build.actions.test.js
test/scripts/build.ui.test.js
test/scripts/deploy.actions.test.js
test/scripts/deploy.ui.test.js
test/scripts/dev.test.js
test/scripts/undeploy.actions.test.js
test/scripts/undeploy.ui.test.js

bye bye cna

---

lib/utils.js
package.json
scripts/add.auth.js
test/scripts/add.auth.test.js

Added package binding for auth persist shared package.

Adding persist package binding

---

README.md
doc/api.md
index.js
package.json

ACNA-491 - add jsdoc

---

lib/config-loader.js
lib/utils.js
test/scripts/deploy.ui.test.js

- fix linting & testing for new app hostname
- fix logger undef in `utils.downloadOWJar` 
- fix remote actions env var parsing

fix logger undef, remote actions env var and lint & tests

---

test/scripts/build.ui.test.js

partial unit tests & coverage, merged to be able to work w/ mutliple persons on it

test build ui if no frontend

---

doc/add-auth.md

doc for add.auth

---

lib/config-loader.js
lib/utils.js
scripts/dev.js
scripts/undeploy.ui.js
test/jest.setup.js
test/scripts/dev.test.js
test/scripts/undeploy.ui.test.js

partial tests for runDev
some fixes

partial runDev tests and fix for termination error message

---

lib/config-loader.js
lib/utils.js
scripts/build.ui.js
scripts/dev.js
test/__fixtures__/sample-app/manifest.yml
test/common.test.js
test/scripts/add.auth.test.js
test/scripts/build.ui.test.js
test/scripts/dev.test.js

fix local dev and config gen

---

scripts/dev.js

change ow url and fix dev cmd cleanup

---

lib/config-loader.js

fix for REMOTE_ACTIONS

---

scripts/dev.js

ow jar downloads docker images on first usage, be gentle with slow connections

increase ow dev timeout to 60s

---

lib/config-loader.js
lib/utils.js
package.json
scripts/build.ui.js
scripts/deploy.ui.js
scripts/dev.js
scripts/undeploy.ui.js
test/common.test.js
test/jest.setup.js
test/lib/utils.test.js
test/scripts/build.ui.test.js
test/scripts/deploy.ui.test.js
test/scripts/dev.test.js

Support for actions to use same domain as static content to support cookies
To support auth workflows
unit tests
manual testing with aio:app deploy command
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ x] My code follows the code style of this project.
- [x ] I have read the **CONTRIBUTING** document.
- [x ] I have added tests to cover my changes.
- [ x] All new and existing tests passed.

Cdn action urls

---

lib/utils.js
test/scripts/build.ui.test.js

fix non web action urls

---

test/scripts/dev.test.js

fix expected app files test

---

lib/utils.js
package.json
scripts/dev.js
test/__mocks__/parcel-bundler.js
test/lib/utils.test.js
test/scripts/dev.test.js

Serve with Parcel and use https
Cannot load in various environments without a cert

Parcel serve

---

bin/cna-scripts.js
scripts/dev.js

show only error logs for openwhisk-jar and parcel serve

cleaner dev logs

---

bin/cna-scripts.js
doc/api.md
index.js
scripts/dev.js
scripts/logs.js
test/scripts/logs.test.js

add log command

---

package.json

chore(package): update aws-sdk to version 2.600.0

---

scripts/dev.js
test/scripts/dev.test.js

Use port returned by bundler

---

lib/utils.js
scripts/deploy.actions.js
scripts/dev.js
test/scripts/deploy.actions.test.js
test/scripts/dev.test.js

fix for https://github.com/adobe/aio-cli-plugin-app/issues/91

expose action urls on deploy and run

---

lib/utils.js
test/scripts/deploy.actions.test.js

partial fix for https://github.com/adobe/aio-cli-plugin-app/issues/173

fix urls for backend only projects

---

lib/utils.js
package.json
scripts/deploy.actions.js
scripts/undeploy.actions.js
test/scripts/deploy.actions.test.js

**Merge after aio-cli-plugin-runtime release and version bump**

adobe auth annotation only for I/O Runtime host

---

scripts/build.actions.js

Minor edit to webpack config
Added .json to the list of extensions to resolve in webpack config to solve an issue with deploying an action with newrelic dependency
I need to have newrelic library in my action to report metrics to newrelic. https://www.npmjs.com/package/newrelic
When I include newrelic as a dependency and deploy my code using `aio app deploy`, i get errors because of webpack. 
I found this answer that solves my problem by adding ".json" to the list of resolve.extensions in Webpack config: https://github.com/newrelic/node-native-metrics/issues/70

Minor edit to webpack config

---

scripts/dev.js
test/scripts/dev.test.js

fix for https://github.com/adobe/aio-cli-plugin-app/issues/163
- options.skipActions option in dev script 
- breaking change rename bundleOption to options.parcel

support run dev with skip actions

---

package.json
scripts/dev.js
test/__mocks__/@adobe/aio-lib-core-logging.js
test/__mocks__/parcel-bundler.js
test/scripts/build.actions.test.js
test/scripts/dev.test.js

fix for https://github.com/adobe/aio-cli-plugin-app/issues/127
do not process.exit

Fix broken bash shell after aio app run

---

test/scripts/dev.test.js

Unit tests running time is now down to 9 secs

Speeding up unit tests

---

scripts/dev.js
test/scripts/dev.test.js

debug config was broken when require-adobe-auth + aio app run --local

fix local dev debug config

---

lib/config-loader.js
lib/utils.js
scripts/deploy.actions.js
test/scripts/deploy.actions.test.js

depends on https://github.com/adobe/aio-cli-plugin-runtime/pull/170
tested manually against an headless app and spa => works

auto switch auth validator + fix for deploy action with custom package

---

lib/utils.js
package.json
scripts/logs.js
test/scripts/deploy.actions.test.js
test/scripts/logs.test.js
test/scripts/undeploy.actions.test.js

Fixes https://github.com/adobe/aio-app-scripts/issues/119
Fixes https://github.com/adobe/aio-cli-plugin-runtime/issues/178

fix: replace openwhisk with runtimelib and fix rules undeployment

---

.gitignore
bin/openwhisk-standalone-config/runtimes.json
lib/owlocal.js
lib/utils.js
scripts/dev.js
test/__fixtures__/named-package/manifest.yml
test/__fixtures__/sample-app-reduced/manifest.yml
test/__fixtures__/sample-app/manifest.yml
test/scripts/deploy.actions.test.js
test/scripts/dev.test.js

relates to https://github.com/adobe/generator-aio-app/pull/83
- wskdebug with kind argument 
- local ow jar supports both adobe node 10 and 12 images
- new ow jar build uploaded at https://dl.bintray.com/adobeio-firefly/aio/:openwhisk-standalone.jar

support node 12

---

lib/utils.js
package.json
test/scripts/deploy.actions.test.js
test/scripts/undeploy.actions.test.js

This pr moved runtime specific functionality to the aio-lib-runtime module, next step will be to move deploy/undeploy-action completely and have aio-cli-plugin-app call aio-lib-runtime directly to complete these ops.

runtime lib

---

lib/utils.js
package.json
scripts/build.actions.js
test/__fixtures__/sample-app-includes/actions/action.js
test/__fixtures__/sample-app-includes/includeme.txt
test/__fixtures__/sample-app-includes/manifest.yml
test/__fixtures__/sample-app-includes/package.json
test/lib/utils.test.js
test/scripts/build.actions.test.js

Support multiple forms of include, as defined by wskdeploy
adobe/aio-cli#204

Manifest includes

---

lib/utils.js
test/scripts/deploy.actions.test.js

passing imsOrgId to syncProject

---

src/deploy-web.js
test/src/deploy-web.test.js

Better error message

---

src/bundle.js

Fix Run debugger

---

package.json

bump dependency

---

.gitignore
e2e/e2e.js

npm run e2e 
(with runtime credentials in an .env file in the root)

fix: e2e failure (parcel v2 upgrade)

---

src/bundle.js
test/src/bundle.test.js

Allow passing of flag to turn optimization on/off

Web optimize

---

src/bundle.js

feat: allow entries globs for multipage apps

---

lib/remote-storage.js
package.json
test/lib/remote-storage.test.js

fix: credential expiration for @aws-sdk/client-s3 v3.624.0 and greater
